### ISSUE TITLE
ubuntu 16.04 autocomplete causes error

### ISSUE THREAD

**Issue by markoffk** [amsdard/yake#12]
yake <TAB PRESSED> causes following error:
awk: line 1: syntax error at or near ,

Issue probably located in /etc/bash_completion.d/yake_completion.sh in following line:
YAKEFILE=$(echo $COMP_LINE | awk 'match($0, / YAKEFILE[ =]([^ ]+)/, awkrules) {print awkrules[1]}')

**Comment by markoffk** [comment]
Ubuntu 16 by default using mawk underhood.
fix:
sudo apt-get install gawk

**Comment by krzysztof-kabala** [comment]
fixed in v2.0
